# @package paths

root: "${hydra:runtime.cwd}"
log:  "${paths.root}/logs"

# Input data - Downloaded and preprocessed by DataPreprocessor
data: "${paths.root}/data"

# Model results - Written by DataExporter, one subdirectory per simulation: {results}/{label}/
results: "${paths.root}/results"
